from turtle import mainloop, Turtle, Screen
import sys


class Car(Turtle):
    def __init__(self):
        Turtle.__init__(self)
        self._init_obj()
        self.speed(0)

    def _init_obj(self):
        self._body_paint()
        self._body_outline()
        self._body_objects()

    def _body_paint(self):
        self.pu()
        self.goto(-600, 0)
        self.pd()
        self.color("red")
        self.forward(600)

        self.color('lightgray')
        self.begin_fill()
        self.left(45)
        self.forward(150)
        self.left(45)
        self.forward(50)
        self.left(135)
        self.forward(150)
        self.left(45)
        self.forward(50)
        self.left(180)
        self.forward(50)
        self.end_fill()

        self.color('lightgray')
        self.begin_fill()
        self.setheading(0)
        self.left(45)
        self.forward(150)
        self.left(135)
        self.forward(150)
        self.left(45)
        self.forward(150)
        self.left(135)
        self.forward(150)
        self.left(180)
        self.forward(150)
        self.end_fill()


        self.color("lightblue")
        self.begin_fill()
        self.setheading(0)
        self.left(45)
        self.forward(150)
        self.left(90)
        self.forward(100)
        self.left(90)
        self.forward(150)
        self.left(90)
        self.forward(100)
        self.left(180)
        self.forward(100)
        self.end_fill()

        self.color('darkgray')
        self.begin_fill()
        self.setheading(0)
        self.left(45)
        self.forward(150)
        self.left(135)
        self.forward(150)
        self.left(45)
        self.forward(150)
        self.left(135)
        self.forward(150)
        self.left(180)
        self.forward(150)
        self.end_fill()

        self.left(90)
        self.forward(50)
        self.setheading(0)

        self.color('lightgray')
        self.begin_fill()
        self.left(45)
        self.forward(150)
        self.left(45)
        self.forward(50)
        self.left(135)
        self.forward(150)
        self.left(45)
        self.forward(50)
        self.end_fill()

        self.color('lightgray')
        self.begin_fill()
        self.setheading(0)
        self.left(45)
        self.forward(150)
        self.left(135)
        self.forward(229.29)
        self.left(45)
        self.forward(150)
        self.left(135)
        self.forward(229.29)
        self.left(180)
        self.forward(229.29)
        self.end_fill()

        self.left(90)
        self.forward(70.71)
        self.setheading(0)

        self.color('lightgray')
        self.begin_fill()
        self.left(45)
        self.forward(150)
        self.left(45)
        self.forward(70.71)
        self.left(135)
        self.forward(150)
        self.left(45)
        self.forward(70.71)
        self.end_fill()

    def _body_outline(self):
        self.color('black')
        self.setheading(0)

        self.forward(600)

        self.left(45)
        self.forward(150)
        self.left(45)
        self.forward(50)
        self.left(135)
        self.forward(150)
        self.left(45)
        self.forward(50)
        self.left(180)
        self.forward(50)

        self.setheading(0)
        self.left(45)
        self.forward(150)
        self.left(135)
        self.forward(150)
        self.left(45)
        self.forward(150)
        self.left(135)
        self.forward(150)
        self.left(180)
        self.forward(150)

        self.setheading(0)
        self.left(45)
        self.forward(150)
        self.left(90)
        self.forward(100)
        self.left(90)
        self.forward(150)
        self.left(90)
        self.forward(100)
        self.left(180)
        self.forward(100)

        self.setheading(0)
        self.left(45)
        self.forward(150)
        self.left(135)
        self.forward(150)
        self.left(45)
        self.forward(150)
        self.left(135)
        self.forward(150)
        self.left(180)
        self.forward(150)

        self.left(90)
        self.forward(50)
        self.setheading(0)

        self.left(45)
        self.forward(150)
        self.left(45)
        self.forward(50)
        self.left(135)
        self.forward(150)
        self.left(45)
        self.forward(50)

        self.setheading(0)
        self.left(45)
        self.forward(150)
        self.left(135)
        self.forward(229.29)
        self.left(45)
        self.forward(150)
        self.left(135)
        self.forward(229.29)
        self.left(180)
        self.forward(229.29)


        self.left(90)
        self.forward(70.71)
        self.setheading(0)

        self.left(45)
        self.forward(150)
        self.left(45)
        self.forward(70.71)
        self.left(135)
        self.forward(150)
        self.left(45)
        self.forward(70.71)

    def _body_objects(self):
        self.color('black')
        self.setheading(0)

        self.forward(600)

        self.left(45)
        self.pu()
        self.forward(15)
        self.setheading(0)
        self.left(45)
        self.forward(45)
        self.pd()
        self.color("yellow")
        self.circle(10)

        '''
        self.left(45)
        self.forward(50)
        self.left(135)
        self.forward(150)
        self.left(45)
        self.forward(50)
        self.left(180)
        self.forward(50)

        self.setheading(0)
        self.left(45)
        self.forward(150)
        self.left(135)
        self.forward(150)
        self.left(45)
        self.forward(150)
        self.left(135)
        self.forward(150)
        self.left(180)
        self.forward(150)

        self.setheading(0)
        self.left(45)
        self.forward(150)
        self.left(90)
        self.forward(100)
        self.left(90)
        self.forward(150)
        self.left(90)
        self.forward(100)
        self.left(180)
        self.forward(100)

        self.setheading(0)
        self.left(45)
        self.forward(150)
        self.left(135)
        self.forward(150)
        self.left(45)
        self.forward(150)
        self.left(135)
        self.forward(150)
        self.left(180)
        self.forward(150)

        self.left(90)
        self.forward(50)
        self.setheading(0)

        self.left(45)
        self.forward(150)
        self.left(45)
        self.forward(50)
        self.left(135)
        self.forward(150)
        self.left(45)
        self.forward(50)

        self.setheading(0)
        self.left(45)
        self.forward(150)
        self.left(135)
        self.forward(229.29)
        self.left(45)
        self.forward(150)
        self.left(135)
        self.forward(229.29)
        self.left(180)
        self.forward(229.29)


        self.left(90)
        self.forward(70.71)
        self.setheading(0)

        self.left(45)
        self.forward(150)
        self.left(45)
        self.forward(70.71)
        self.left(135)
        self.forward(150)
        self.left(45)
        self.forward(70.71)
'''
def main():
    screen = Screen()
    screen.title("First 3D vehicle with python")
    screen.bgcolor('white')

    obj = Car()
    return 'EVENT LOOP'


if __name__ == '__main__':
    sys.stdout.write(main())
    mainloop()
